### PR TITLE
Add goals listing & updating, use Alfred env vars

### PR DESCRIPTION
**Pull request by jeffbyrnes**
This adds a new functionality: goal listing & updating!

Additionally, it simplifies how the user-supplied variables are set, makign them true env vars.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@chadhs heads-up! This depends on #10, so you’ll see those commits in here, unfortunately. I can close & re-open this PR once that merges in, to more clearly see this separately, if you like.

**Comment by chadhs** [comment]
#10 is merged in and i can squash and merge when this is all set @jeffbyrnes :-)

**Comment by chadhs** [comment]
@jeffbyrnes would you mind reconciling the conflicts, i'll review the listing ruby code in the mean time; looks awesome!

**Comment by jeffbyrnes** [comment]
@chadhs sure thing! I'm away on holiday until Monday; I'll tackle this then. Thanks!

**Comment by jeffbyrnes** [comment]
@chadhs all set!

**Comment by jeffbyrnes** [comment]
Rebased this once more against the current `master`.

The list code could use some caching, which I have in a half-built fashion, but it works as-is.

**Comment by chadhs** [comment]
Thank you Jeff, I need to get this taken care of soon.

-- 
Chad Stovern // @chadhs

On January 30, 2017 at 6:00:32 AM, Jeff Byrnes (notifications@github.com) wrote:

Rebased this once more against the current master.

The list code could use some caching, which I have in a half-built fashion, but it works as-is.

**Comment by chadhs** [comment]
@jeffbyrnes hey there.  i was going to release this today, but the workflow file had some hardcoded values in the embedded ruby script.

if i remove that script entirely and wire the script filter directly to the post notification it outputs the goal id when i select a goal.

did you have another script that was supposed to take that id as input and call the api to mark that item as done?  if not i could likely do that to finish this up.

**Comment by chadhs** [comment]
^ also let me know if i misunderstood the approach or anything else.  👍

**Comment by jeffbyrnes** [comment]
@chadhs I… may have forgotten that part? 🤦‍♂️ I’m re-reading my own code now, a few months later.

For reasons of version control, I’m inclined to keep the script separate, but defer to you as the owner.

I had some half-baked caching sitting around, if you want me to push that up in a WIP commit or on a separate branch.

Also, this could probably be two PRs.

**Comment by chadhs** [comment]
Without that script I don’t think anyone will be able to mark items as done, can you see what you have and share?

-- 
Chad Stovern // @chadhs

On April 24, 2017 at 3:06:36 PM, Jeff Byrnes (notifications@github.com) wrote:

@chadhs I… may have forgotten that part? 🤦‍♂️ I’m re-reading my own code now, a few months later.

For reasons of version control, I’m inclined to keep the script separate, but defer to you as the owner.

I had some half-baked caching sitting around, if you want me to push that up in a WIP commit or on a separate branch.

Also, this could probably be two PRs.

**Comment by jeffbyrnes** [comment]
@chadhs sorry, it was probably unclear. I have some _other_ code, related to caching, sitting around unfinished. I’m happy to push that up in a separate PR, but it doesn’t have anything to do w/ marking items as done.

**Comment by chadhs** [comment]
I'll have to try it again, I wasn't able to get the mark as done part working.

If you add the workflow as a second entry and plug in your envs does it work for you?

**Comment by jeffbyrnes** [comment]
Lemme give it a spin.

**Comment by jeffbyrnes** [comment]
Ah, I see what’s going on; I’m using some older code that works, but is super janky. Lemme polish this up & get it pushed up here.

**Comment by chadhs** [comment]
rock on!  i'll test/verify and merge this in after.  thank you.

**Comment by jeffbyrnes** [comment]
@chadhs ok, that should do it. I’ve added the previously-missing `list.rb` script, and updated the workflow from my own copy that I’ve been using for some time.

It’s still _super_ slow b/c no caching. I’m gonna try & quickly knock that out, but this is ready to rock now.

**Comment by chadhs** [comment]
see PR 13

**Comment by jeffbyrnes** [comment]
Refactored as #13 (links are nice)

**Comment by chadhs** [comment]
good call thx!

**Pull request closed without merging**
